name: CI

on:
  workflow_dispatch:
  release:
  push:
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        arch: [arm64]  # Оставили только arm64
        include:
          # Убрали x86_64 для macOS
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 16

      # Setup dependencies for macOS using only setuptools
      - name: Setup macOS Dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools

      # Setup Linux dependencies
      - name: Setup Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libxcb-xkb-dev libxkbfile-dev libxinerama-dev

      # Install packages without running scripts
      - name: Install Packages
        run: npm i --ignore-scripts

      # Build only if version tag is not present
      - name: Build
        run: npm run build -- --all --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v') != true
        env:
          ARCH: ${{ matrix.arch }}

      # Remove steps for building and publishing prebuilds
      # Build and publish steps have been removed as requested
