name: CI

on:
  workflow_dispatch:  # Позволяет вручную запускать workflow
  release:  # Срабатывает на создание релиза
  push:  # Срабатывает на пуш коммитов
  pull_request:  # Срабатывает на создание пулл-запросов
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        arch: [arm64]  # Убираем x86_64, оставляем только arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Устанавливаем Node.js версии 16
          node-version: 16

      - name: Setup macOS Dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install python@3.10  # Устанавливаем Python 3.10
          brew link --overwrite python@3.10 --force  # Связываем

      - name: Setup Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libxcb-xkb-dev libxkbfile-dev libxinerama-dev

      - name: Install Packages
        run: npm install --ignore-scripts

      # Сборка только если версия тега отсутствует
      - name: Build
        run: npm run build -- --all --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v') != true
        env:
          ARCH: ${{ matrix.arch }}

      # Сборка и публикация только если версия тега присутствует
      - name: Build & Publish Prebuilds
        run: npm run build:ci -- --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Убираем шаг публикации в NPM
